apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redid

spec:
  selector:
    matchLabels:
      app: redis

  template:
    metadata:
      labels:
        app: redis

    spec:
      containers:
        - name: redis
          image: redis:7.4.0
          ports:
            - containerPort: 6379
#          env:
#            - name: REDIS_HOST
#              valueFrom:
#                configMapKeyRef:
#                  name: data-service-configmap
#                  key: redis-host
#
#            - name: REDIS_PORT
#              valueFrom:
#                 configMapKeyRef:
#                  name: data-service-configmap
#                  key: redis-port
          volumeMounts:
            - mountPath: /var/lib/redis/data
              name: redis-persistent-storage
      volumes:
        - name: redis-persistent-storage
          persistentVolumeClaim:
            claimName: redis-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis

spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      name: redis
      port: 6379
      targetPort: 6379
  type: ClusterIP

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi